version: '2'
services:
  php:
    build: ./php
    ports:
      - "80:80"
    volumes:
      - ./php/php_project:/var/www/html/www.carlitosdroid.com
    depends_on:
      - mysql
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"


   

    
